# Generated by Django 5.2.6 on 2026-09-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_profile_languages_de_profile_languages_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, help_text='username, no @', max_length=64),
        ),
    ]
