# Generated by Django 5.2.6 on 2026-09-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_profile_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, help_text="The top of the post's page and the preview image when it is shared. Landscape, about 1600×900 px.", upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='The portrait: home hero, about, résumé and the business card, and the preview image when a page is shared. Square, at least 700×700 px.', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume_file',
            field=models.FileField(blank=True, help_text='The file behind every «download résumé» button (home, résumé page, footer). PDF.', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover',
            field=models.ImageField(blank=True, help_text="The project's card on the home and projects pages, the top of its own page, and the preview image when it is shared. Landscape, about 1600×1000 px; the cards crop it, so keep the subject in the middle. Empty shows the pastel cover art.", upload_to='projects/'),
        ),
    ]
